In [1]:
print('Hello World')

Hello World


### Array operations

In [4]:
2 ** 32 

4294967296

In [5]:
import numpy as np

In [6]:
num= np.array([56,26,34,89,58,25])

In [7]:
print(num)

[56 26 34 89 58 25]


In [8]:
num

array([56, 26, 34, 89, 58, 25])

In [9]:
num.dtype

dtype('int32')

In [10]:
num.size

6

In [12]:
num[3]

89

In [13]:
num[3]=14
num

array([56, 26, 34, 14, 58, 25])

In [14]:
num= np.array([14,54,26,89.45,23])

In [15]:
num

array([14.  , 54.  , 26.  , 89.45, 23.  ])

In [16]:
num.dtype

dtype('float64')

In [17]:
num[1]

54.0

In [19]:
num= np.array([14,54,26,89,23,True])
num

array([14, 54, 26, 89, 23,  1])

In [20]:
num= np.array([14,54,26,89,23,'hello'])
num

array(['14', '54', '26', '89', '23', 'hello'], dtype='<U11')

In [22]:
city = np.array(['पुणे' ,'मुंबई' ,'नागपुर' ,'नाशिक' ])

In [23]:
city

array(['पुणे', 'मुंबई', 'नागपुर', 'नाशिक'], dtype='<U6')

In [24]:
city[2]

'नागपुर'

In [25]:
city[0]*5

'पुणेपुणेपुणेपुणेपुणे'

In [42]:
num= np.array([14,54,26,89,23])

In [43]:
num.max()

89

In [44]:
num.cumsum()

array([ 14,  68,  94, 183, 206], dtype=int32)

In [45]:
num.sum()

206

In [46]:
num.std()

27.389048906451645

In [47]:
x=[45,12]
x*2

[45, 12, 45, 12]

In [48]:
x=[1,5,34]
x*3

[1, 5, 34, 1, 5, 34, 1, 5, 34]

In [49]:
num*2

array([ 28, 108,  52, 178,  46])

In [50]:
num/10

array([1.4, 5.4, 2.6, 8.9, 2.3])

In [55]:
num>40

array([False,  True, False,  True, False])

In [56]:
42 in num

False

In [57]:
58 not in num

True

In [61]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [60]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [63]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [65]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [66]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [68]:
np.arange(1,10,.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [69]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [75]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [78]:
x= np.array([[2,5,4],[5,8,7]])


In [79]:
x

array([[2, 5, 4],
       [5, 8, 7]])

In [80]:
x.shape

(2, 3)

In [81]:
x.size

6

In [82]:
#0 dimensinal scaler
#1 d vector
#2,3 d matrix
#more than 4 tensor


In [83]:
x.ndim

2

In [84]:
x[1][2]

7

In [85]:
x.reshape(3,2)

array([[2, 5],
       [4, 5],
       [8, 7]])

In [86]:
x.reshape(6,1)

array([[2],
       [5],
       [4],
       [5],
       [8],
       [7]])

In [89]:
x.reshape(3,-1)

array([[2, 5],
       [4, 5],
       [8, 7]])

In [90]:
x.flatten()

array([2, 5, 4, 5, 8, 7])

**Series Operations**

In [91]:
import pandas as pd


In [92]:
s=pd.Series([54,65,24,34,68,45])


In [93]:
s

0    54
1    65
2    24
3    34
4    68
5    45
dtype: int64

In [94]:
s[2]

24

In [95]:
s[2]=23

In [96]:
s

0    54
1    65
2    23
3    34
4    68
5    45
dtype: int64

In [98]:
s=pd.Series([54,65,24,34,68,45] , index = range(100,106))


In [99]:
s

100    54
101    65
102    24
103    34
104    68
105    45
dtype: int64

In [100]:
s[104]

68

In [101]:
s.dtype

dtype('int64')

In [102]:
s.size

6

**DataFrame Operations**



In [113]:
x=pd.Series([1,2,3])
y=pd.Series(['Anshu','ANSH','ram'])
z=pd.Series([45.12,46.23,78.56])

In [114]:
df=pd.DataFrame({
    'roll':x,
    'name': y,
    'marks':z
})


In [115]:
df

roll   name  marks
0     1  Anshu  45.12
1     2   ANSH  46.23
2     3    ram  78.56

In [116]:
df.shape


(3, 3)

In [117]:
df.columns

Index(['roll', 'name', 'marks'], dtype='object')

In [118]:
df.size

9

In [119]:
df.T

0      1      2
roll       1      2      3
name   Anshu   ANSH    ram
marks  45.12  46.23  78.56

In [121]:
list(s)

[54, 65, 24, 34, 68, 45]

In [122]:
tuple(s)

(54, 65, 24, 34, 68, 45)

In [123]:
set(s)

{24, 34, 45, 54, 65, 68}

In [124]:
s.values

array([54, 65, 24, 34, 68, 45], dtype=int64)

In [125]:
df.values

array([[1, 'Anshu', 45.12],
       [2, 'ANSH', 46.23],
       [3, 'ram', 78.56]], dtype=object)

In [126]:
dict(df)

{'roll': 0    1
 1    2
 2    3
 Name: roll, dtype: int64,
 'name': 0    Anshu
 1     ANSH
 2      ram
 Name: name, dtype: object,
 'marks': 0    45.12
 1    46.23
 2    78.56
 Name: marks, dtype: float64}

In [127]:
x=np.arange(1,101)

In [128]:
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [132]:
x.mean()

50.5

In [133]:
y= np.array([45,68,42,57])

In [134]:
y.mean()

53.0

In [135]:
import os
os.getcwd()

'C:\\Users\\ADMIN'